### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by DarkAxi0m** [telstra/MessagingAPI-SDK-php#1]
In the composer setup area it has [https://github.com/Telstra/Telstra_Messaging.git ](https://github.com/Telstra/Telstra_Messaging.git ) not [https://github.com/telstra/MessagingAPI-SDK-php.git](https://github.com/telstra/MessagingAPI-SDK-php.git)

Is there a release planed? we try not to use "*@dev" requires. 
Also is there plans to add this to packagist?

**Comment by developersteve** [comment]
Hi DarkAxi0m, 

Thanks for picking that up, updating now. Would love to be able to get SDKs listed with respective repositories like packagist.
