### ISSUE TITLE
MessagingApi getSMSStatus blank response 

### ISSUE THREAD

**Issue by DarkAxi0m** [telstra/MessagingAPI-SDK-php#2]
Doing a call do getSMSStatus with a valid message id returns a blank class.

> $status Telstra_Messaging\Model\OutboundPollResponse (1)
→protected container -> array (4)
to => null
received_timestamp => null
sent_timestamp => null
delivery_status => null

In the MessagingApi class, the api call in the getSMSStatusWithHttpInfo function is returning a JSON array but the ObjectSerializer::deserialize dose not seem to expect it.
`[ { "to": "+XXXXXXXXX", "sentTimestamp": "2018-02-08T15:57:53+10:00", "receivedTimestamp": "2018-02-08T15:57:52+10:00", "deliveryStatus": "DELIVRD" } ]`

**Comment by DarkAxi0m** [comment]
To get it working I have locally changed the  $returnType to 
 `$returnType = '\Telstra_Messaging\Model\OutboundPollResponse[]';`

**Comment by developersteve** [comment]
Pushed 1.0.2 with the fix for this into the dev branch

https://github.com/telstra/MessagingAPI-SDK-php/tree/dev
