### ISSUE TITLE
MessagingApi retrieveSMSResponses not working

### ISSUE THREAD

**Issue by DarkAxi0m** [telstra/MessagingAPI-SDK-php#3]
Calling this returns an array of InboundPollResponses, all blank
> Telstra_Messaging\Model\InboundPollResponse (1)
→protected container -> array (6)
to => null
from => null
body => null
received_timestamp => null
more_messages => null
message_id => null

But the JSON content is 
`{ "status": "RECEIVED", "destinationAddress": "+XXXX", "senderAddress": "+XXXX", "message": "Tests 4", "sentTimestamp": "2018-02-08T16:42:49+10:00" }`

**Comment by developersteve** [comment]
Pushed 1.0.2 with the fix for this into the dev branch

https://github.com/telstra/MessagingAPI-SDK-php/tree/dev
